### ISSUE TITLE
.sql file missing?

### ISSUE THREAD

**Issue by miguel-piste** [fdgd1998/vigalArtesanos-CMS#1]
Hi, I wanted to know if you can share the sql file so that I can access the admin panel on my local host. your development is just what I have been looking for and it will help me to practice. Thanks

**Comment by fdgd1998** [comment]
I have uploaded the .sql file to the repository. I provide the database structure without any data. 
I've uploaded the finished code as of now as well, the same that's live on vigalartesana.es,  there were some missing changes.

**Comment by fdgd1998** [comment]
I've generate a new encryption key for testing, you can see it in the cryptograhic_key.php file. Change this key later on if you plan to upload the code to any hosting.

You will access to the control panel with the user "admin" and password "admin", without the quotes.

Remember to change your settings in connection.php and email_settings.php after your have exported the database in your machine.

In order to make everything work, you'll need to do the following.
- Move cryptograhpic_key.php, connection.php and email_settings.php outside htdocs folder (on the same directory level).
- Copy all the content inside public_html into the root of htdocs.

Your folder tree must see like the following:

__xampp
   |
   |_____htdocs(html_public contents go here)
   |
   |_____cryptographic_key.php
   |_____connection.php
   |_____email_settings.php

You may see some missing elements until you populate the website with contents.

**Comment by miguel-piste** [comment]
Thanks for the instructions, I'm already testing the application.
